version: '3.8'

services:
  discord-bot:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VERSION=${VERSION}
    volumes:
      - .:/app
    restart: always
